# Generated by Django 4.1.7 on 2023-11-10 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryExitTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryTime', models.DateTimeField()),
                ('ExitTime', models.DateTimeField()),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.student')),
            ],
        ),
    ]
