# Generated by Django 4.1.7 on 2023-11-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_entryexittime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryexittime',
            name='EntryTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entryexittime',
            name='ExitTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
